### ISSUE TITLE
How is this different than the "Extension Manager" of JupyterLab?

### ISSUE THREAD

**Issue by enricorotundo** [vidartf/jupyterlab_discovery#11]
I'm referring to this package: https://github.com/jupyter-widgets/ipywidgets/tree/master/packages/jupyterlab-manager

**Comment by vidartf** [comment]
This package was included into the core of jupyterlab as the extension manager package. As such this package has been discontinued, and I keep it around mostly for future reference (git history etc). It says so in the Readme as well, but I guess I could highlight it a little better 😉

**Comment by enricorotundo** [comment]
My bad I didn't read the readme carefully... nice then kudos for you! 
Maybe just mention the it has also been renamed into "Extension Manager" and a link to the new package 😃

**Comment by vidartf** [comment]
PS: The package that you linked is for making ipywidgets work with jupyterlab, and has nothing to do with this package, nor the extension manager in core.
