### ISSUE TITLE
cannot import name '_read_package'

### ISSUE THREAD

**Issue by Tropfchen** [vidartf/jupyterlab_discovery#12]
__read_package_ function was changed to _read_package_ ever since https://github.com/jupyterlab/jupyterlab/commit/61594615f7c23266abc880ddf91fb29737cd899f
I don’t know if refactoring the function and changing "_@jupyterlab/services_" to "_^3.0.0_" in package.json is correct and enough, so I’ll just leave this as an issues.

**Comment by vidartf** [comment]
Note, this package has been merged into Jupyterlab core, see the Readme for details. As such, this package has been discontinued. Let me know if you have any further questions or comments!
