### ISSUE TITLE
jupyterlab_discovery not working after installing few extensions

### ISSUE THREAD

**Issue by astrozot** [vidartf/jupyterlab_discovery#6]
I just installed jupyterlab_discovery on a fresh Anaconda3 environment. Everything worked nicely till I tried to install 3 jupytelab extensions (TOC, LaTeX, and Spell checker). Then suddenly jupyterlab_discovery stopped working: in particular keep showing an empty search result page, even if the search box is empty (in which case I would expect it to show the list of installed extensions).

Any idea on how I could solve this issue?

<img width="335" alt="screen shot 2018-05-13 at 01 50 35" src="https://user-images.githubusercontent.com/2106594/39962480-16debbc8-5650-11e8-9f52-4162cfbdc9e0.png">

**Comment by vidartf** [comment]
Hi, and thanks for the report! Are you on the latest version of the package? I recently saw something similar that I fixed, so that's the first thing I would try.

**Comment by vidartf** [comment]
If that doesn't fix the problem, would you mind checking your server output for warnings/errors, and the same with the browser console?

**Comment by astrozot** [comment]
Hi, thank you for your quick reaction! I installed the package with
```
pip install jupyterlab-discovery
```
Does this use the latest version or should I do something different?

**Comment by vidartf** [comment]
The pip install line should normally upgrade it, but you can check if `pip list` gives you the latest version.

**Comment by astrozot** [comment]
`pip list` shows, among other things,
```
jupyterlab (0.32.1)
jupyterlab-discovery (5.1.1)
jupyterlab-launcher (0.10.5)
```
No error/warning on the server. Instead there are errors shown in the browser console when I touch the search field:

<img width="943" alt="screen shot 2018-05-13 at 10 39 37" src="https://user-images.githubusercontent.com/2106594/39965494-3ba1f912-569a-11e8-8afd-8cb935b5fbc8.png">

**Comment by vidartf** [comment]
Ok, thanks for the console output. I'll try to debug it tomorrow (not at computer currently)!

**Comment by astrozot** [comment]
OK, thank you!

**Comment by vidartf** [comment]
Looking at this now: Which browser are you using?

**Comment by astrozot** [comment]
Safari.

Marco

Il 14 mag 2018, 11:43 +0200, Vidar Tonaas Fauske <notifications@github.com>, ha scritto:

**Comment by vidartf** [comment]
Which version of Safari? The likely cause of the error is the browser not supporting an API that I'm using (https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams/append). However, I've been using that API for a while, so it doesn't make sense for this to suddenly stop working unless you've switched browser. Are there any other errors in the browser console?

**Comment by astrozot** [comment]
Sorry for the late reply. I am running Safari v11.0.1. Indeed the interface seems to work with Chrome 66.0.3359.139.

**Comment by vidartf** [comment]
Hmm. Safari 11.x should support it (https://caniuse.com/#feat=urlsearchparams), so there might be something else that goes wrong. It's especially strange that it stopped working at a certain point. If you start the server with `jupyter lab --debug`, are there any error messages when searching?

**Comment by astrozot** [comment]
I just see two warnings:

[W 15:24:01.665 LabApp] 404 GET /apple-touch-icon-precomposed.png (::1)
72.19ms referer=None
[W 15:24:01.673 LabApp] 404 GET /apple-touch-icon.png (::1) 2.22ms
referer=None

All the rest are standard debugging messages.

**Comment by vidartf** [comment]
I'm kind of stumped. Can you try running these instructions in your browser console while the lab page is open, and share the output:

```js
var url = new URL('discovery/api/extensions', 'http://localhost:8888/');
console.log(url);

url.searchParams.append('refresh', '1');
console.log(url);
```

**Comment by astrozot** [comment]
The first command runs without problems:

Object = {
_fragment: ""
_host: "localhost"
_isInvalid: false
_isRelative: true
_password: null
_path: ["discovery", "api", "extensions"] (3)
_port: "8888"
_query: ""
_scheme: "http"
_schemeData: ""
_url: "discovery/api/extensions"
_username: ""
}

The second one generates an error:

TypeError: undefined is not an object (evaluating 'url.searchParams.append')

Essentially url.searchParams does not exists (it is null).

**Comment by vidartf** [comment]
This should be fixed in the version that is in Jupyterlab core.
