### ISSUE TITLE
Not compatible with JupyterLab v0.33.6 conflicting dependencies

### ISSUE THREAD

**Issue by offchan42** [vidartf/jupyterlab_discovery#9]
I ran `jupyter labextension list` and this is one of the result:
```
jupyterlab_discovery
jupyterlab_discovery v5.1.2 enabled   X

"jupyterlab_discovery@5.1.2" is not compatible with the current JupyterLab
Conflicting Dependencies:
JupyterLab           Extension        Package
>=0.17.2 <0.18.0     >=0.16.0 <0.17.0 @jupyterlab/apputils
>=3.0.3 <4.0.0       >=2.0.0 <3.0.0   @jupyterlab/services
```

**Comment by vidartf** [comment]
Hi! The extension discovery plugin has been integrated into core jupyterlab from 0.33 onwards. You'll need to open your advanced settings editor to enable it because until some things settle down, it is disabled by default.

**Comment by vidartf** [comment]
I'll update the README here as well once it is certain that it will be kept in core.

**Comment by offchan42** [comment]
I opened the Advanced Settings editor and I don't know how to do what you said. How do I enable it?

**Comment by mippos** [comment]
It seems to be renamed as Extension Manager. This worked:
<img width="1909" alt="screen shot 2018-08-07 at 12 08 26" src="https://user-images.githubusercontent.com/2344452/43766283-be33596e-9a3a-11e8-9581-58d77c3a3d13.png">

**Comment by offchan42** [comment]
Aha. Thank you. So I've removed your `jupyterlab-discovery` extension with that Extension Manager now. So sad... 😭

**Comment by haobibo** [comment]
Maybe this is not the right place to ask the question but is there any command (like `jupyter labextension enable xxx`) to enable the Extension Manager from shell/cmd? Does jupyterlab provide command to change user settings?

**Comment by vidartf** [comment]
@haobibo: There were some initial concerns about the extension manager, so it was initially included behind a flag in client side user settings. Currently, I do not know of any ways to change the default user settings from the server (CC @afshin to correct me if I'm wrong). I think the plan is to make the extension manager more easily accessible ones it has matured a little more in core.

**Comment by mocquin** [comment]
Will try this tonight!
Thanks a lot !
